[2019-07-05 12:00:03,696] INFO [GroupCoordinator 1]: Member consumer-1-128dfa94-b88f-4cb9-be80-559e7a6a0993 in group console-consumer-5830 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-07-05 12:00:03,697] INFO [GroupCoordinator 1]: Preparing to rebalance group console-consumer-5830 in state PreparingRebalance with old generation 1 (__consumer_offsets-35) (reason: removing member consumer-1-128dfa94-b88f-4cb9-be80-559e7a6a0993 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-07-05 12:00:03,698] INFO [GroupCoordinator 1]: Group console-consumer-5830 with generation 2 is now empty (__consumer_offsets-35) (kafka.coordinator.group.GroupCoordinator)
[2019-07-05 12:02:36,391] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:53659-6 (kafka.network.Processor)
[2019-07-05 12:02:51,636] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:53680-7 (kafka.network.Processor)
[2019-07-05 12:03:00,671] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:53690-9 (kafka.network.Processor)
[2019-07-05 12:05:46,699] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:53699-10 (kafka.network.Processor)
[2019-07-05 12:06:38,188] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:53741-12 (kafka.network.Processor)
[2019-07-05 12:06:49,031] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:53755-13 (kafka.network.Processor)
[2019-07-05 12:06:52,460] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(dcode_fileParse_XD-1, dcode_fileParse_SKETCH-0) (kafka.server.ReplicaFetcherManager)
[2019-07-05 12:06:52,460] INFO [Partition dcode_fileParse_XD-1 broker=1] dcode_fileParse_XD-1 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-07-05 12:06:52,461] INFO [Partition dcode_fileParse_SKETCH-0 broker=1] dcode_fileParse_SKETCH-0 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-07-05 12:06:52,462] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Shutting down (kafka.server.ReplicaFetcherThread)
[2019-07-05 12:06:52,462] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Stopped (kafka.server.ReplicaFetcherThread)
[2019-07-05 12:06:52,462] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Shutdown completed (kafka.server.ReplicaFetcherThread)
[2019-07-05 12:06:52,479] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(dcode_fileParse_SKETCH-1, dcode_fileParse_XD-0) (kafka.server.ReplicaFetcherManager)
[2019-07-05 12:06:52,479] INFO [Partition dcode_fileParse_SKETCH-1 broker=1] dcode_fileParse_SKETCH-1 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-07-05 12:06:52,480] WARN [LeaderEpochCache dcode_fileParse_SKETCH-1] New epoch entry EpochEntry(epoch=1, startOffset=0) caused truncation of conflicting entries ListBuffer(EpochEntry(epoch=0, startOffset=0)). Cache now contains 1 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2019-07-05 12:06:52,482] INFO [Partition dcode_fileParse_XD-0 broker=1] dcode_fileParse_XD-0 starts at Leader Epoch 1 from offset 3. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-07-05 12:06:52,532] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-07-05 12:06:52,533] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
[2019-07-05 12:06:52,533] INFO [KafkaServer id=1] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-07-05 12:06:52,538] WARN [KafkaServer id=1] Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-07-05 12:06:52,539] WARN [KafkaServer id=1] Error during controlled shutdown, possibly because leader movement took longer than the configured controller.socket.timeout.ms and/or request.timeout.ms: Connection to localhost:9092 (id: 0 rack: null) failed. (kafka.server.KafkaServer)
[2019-07-05 12:06:52,987] INFO Unable to read additional data from server sessionid 0x10000ce87810004, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:54,463] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:54,464] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:56,196] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:56,197] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:57,543] WARN [KafkaServer id=1] Retrying controlled shutdown after the previous attempt failed... (kafka.server.KafkaServer)
[2019-07-05 12:06:57,721] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:57,722] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:57,824] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-07-05 12:06:59,370] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:06:59,372] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:00,740] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:00,740] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:02,179] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:02,179] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:03,983] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:03,984] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:05,325] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:05,326] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:07,256] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:07,256] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:08,463] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:08,464] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:10,329] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:10,330] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:10,557] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-07-05 12:07:12,094] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-07-05 12:07:12,095] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
