[2019-08-03 19:00:45,326] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-08-03 19:00:52,658] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(python-0, java-1, c-1) (kafka.server.ReplicaFetcherManager)
[2019-08-03 19:00:52,659] INFO [Partition python-0 broker=1] python-0 starts at Leader Epoch 1 from offset 34. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-08-03 19:00:52,660] INFO [Partition java-1 broker=1] java-1 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-08-03 19:00:52,661] INFO [Partition c-1 broker=1] c-1 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-08-03 19:00:52,663] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Shutting down (kafka.server.ReplicaFetcherThread)
[2019-08-03 19:00:52,664] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Shutdown completed (kafka.server.ReplicaFetcherThread)
[2019-08-03 19:00:52,664] INFO [ReplicaFetcher replicaId=1, leaderId=0, fetcherId=0] Stopped (kafka.server.ReplicaFetcherThread)
[2019-08-03 19:00:52,699] INFO [ReplicaFetcherManager on broker 1] Removed fetcher for partitions Set(java-0, c-0, python-1) (kafka.server.ReplicaFetcherManager)
[2019-08-03 19:00:52,699] INFO [Partition java-0 broker=1] java-0 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-08-03 19:00:52,700] WARN [LeaderEpochCache java-0] New epoch entry EpochEntry(epoch=1, startOffset=0) caused truncation of conflicting entries ListBuffer(EpochEntry(epoch=0, startOffset=0)). Cache now contains 1 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2019-08-03 19:00:52,701] INFO [Partition c-0 broker=1] c-0 starts at Leader Epoch 1 from offset 0. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-08-03 19:00:52,701] WARN [LeaderEpochCache c-0] New epoch entry EpochEntry(epoch=1, startOffset=0) caused truncation of conflicting entries ListBuffer(EpochEntry(epoch=0, startOffset=0)). Cache now contains 1 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2019-08-03 19:00:52,702] INFO [Partition python-1 broker=1] python-1 starts at Leader Epoch 1 from offset 37. Previous Leader Epoch was: 0 (kafka.cluster.Partition)
[2019-08-03 19:00:52,775] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-08-03 19:00:52,776] INFO [KafkaServer id=1] shutting down (kafka.server.KafkaServer)
[2019-08-03 19:00:52,777] INFO [KafkaServer id=1] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-08-03 19:00:52,785] WARN [KafkaServer id=1] Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-08-03 19:00:52,785] WARN [KafkaServer id=1] Error during controlled shutdown, possibly because leader movement took longer than the configured controller.socket.timeout.ms and/or request.timeout.ms: Connection to localhost:9092 (id: 0 rack: null) failed. (kafka.server.KafkaServer)
[2019-08-03 19:00:53,226] INFO Unable to read additional data from server sessionid 0x1000003e9b30001, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:54,061] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:49609-1 (kafka.network.Processor)
[2019-08-03 19:00:54,061] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9093-127.0.0.1:49611-2 (kafka.network.Processor)
[2019-08-03 19:00:54,572] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:54,572] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:55,821] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:55,821] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:57,074] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:57,074] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:57,787] WARN [KafkaServer id=1] Retrying controlled shutdown after the previous attempt failed... (kafka.server.KafkaServer)
[2019-08-03 19:00:58,639] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:58,640] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:00:58,743] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-08-03 19:01:00,721] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:01:00,722] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:01:02,087] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:01:02,087] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:01:02,304] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-08-03 19:01:03,320] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-03 19:01:03,321] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
